# Generated by Django 5.1.4 on 2025-01-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_orderitem_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tracking_number',
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(default='x', max_length=100),
        ),
    ]
