# Generated by Django 5.1.4 on 2025-01-22 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_remove_order_tracking_number_alter_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
