# Generated by Django 5.1.4 on 2025-01-22 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_payment_razorpay_order_id_payment_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
    ]
