# Generated by Django 5.1.4 on 2025-01-20 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_order_city_order_country_order_landmark_and_more'),
        ('payments', '0004_remove_payment_total_amount_remove_payment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to='orders.order'),
        ),
    ]
